services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=3000
      # - DB_URL=postgres://avi:avi@postgres:5432/url_shortener?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_USER=avi
      - DB_PASSWORD=avi
      - DB_PORT=5432
      - DB_NAME=url_shortener

  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
  
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: avi
      POSTGRES_PASSWORD: avi
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg-isready", "-U avi"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
