name: url-shortner

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.changes.outputs.client_any_changed }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: detect changes
        id: changes
        uses: tj-actions/changed-files@v46.0.1
        with:
          files_yaml: |
            client:
              - 'client/**'

  build-push-to-ecr:
    needs: detect-changes
    runs-on: ubuntu-latest
    # if: needs.detect-changes.outputs.client == 'true'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: us-east-1
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: docker build -t url-shortner-client ./client
      - name: Tag image
        run: docker tag url-shortner-client:${GITHUB_SHA} ${{secrets.ECR_REPOSITORY_URI}}:${{github.sha}}
      - name: Push image to ECR
        run: docker push ${{secrets.ECR_REPOSITORY_URI}}:${{ github.sha}}

